### ISSUE TITLE
Initial TODO

### ISSUE THREAD

**Issue by ebi-yade** [ebi-yade/jex#1]
- [x] Parcelおよび拡張用の依存をインスコ
- [x] このあたり斜め読み
  - [Chrome 拡張機能のマニフェストファイルの書き方](https://qiita.com/mdstoy/items/9866544e37987337dc79)
  - [Chrome拡張　備忘録　１から１０まで](https://qiita.com/Tachibana446/items/696bb93bd4a23525cbb0)
- [x] manifest v2 一旦書く
- [x] 適当なアイコン作って manifest 登録する
- [x] 一旦 yarn start が動くようにする
- [x] manifest v3 に移行する
- [x] OAuth まわりのケア 
- [x] Text-to-Speech API による
- [x] Service Worker からタブへの情報パッシング
- [x] Audio 読み上げ
